name: Build & Upload Site
# Run on pushes to the main branch
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.5'
        bundler-cache: true
    # Install the gems in the gemfile & install lftp
    - name: Setup Environment.
      run: |
        bundle install
        sudo apt-get update -qy
        sudo apt-get install -y lftp
    
    # Build the site
    - name: Build Site with Jekyll.
      run: JEKYLL_ENV=production bundle exec jekyll build
    
    # Looks kind of complicated but just uploads the content of _site folder to the ftp server. It does not upload the _site folder itself.
    - name: Upload site to FTP.
      env: 
        ftp_location: ${{ secrets.FTP_LOCATION }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        ftp_folder: ${{ secrets.FTP_FOLDER }}
      run: |
        lftp -e "open $ftp_location; set ssl:verify-certificate false; set net:reconnect-interval-base 1; user $ftp_username $ftp_password; mirror -X .* -X .*/ --no-umask --reverse --verbose --delete _site/ $ftp_folder; bye"